version: "0.1"

services:

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    container_name: kafka

  stock-price:
    build:
      context: ./Stock_NVDA
      dockerfile: Dockerfile
    container_name: stock-price

